### ISSUE TITLE
replace select version strings in files using regex

### ISSUE THREAD

**Issue by hkiang01** [hkiang01/version_upper#13]
## Problem
There are cases where you only want to replace a single string in a given file, but not all instances of the "current version" in said file. For example, consider the following `appChart.yaml`, which is created from `helm create app` (with comments removed):

```yaml
apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 1.16.0
appVersion: 1.16.0
```

It's possible that both `version` and `appVersion` match the version-upper config's current version, but you only want to replace `appVersion`.

## Potential Solution
[bump2version](https://github.com/c4urself/bump2version/#search-) has `search`, but one should be careful such that the following doesn't occur:

```yaml
appVersion: appVersion: 1.16.1
```
